openapi: 3.1.0
info:
  title: Malygos API
  description: |
    An API to create Kubernetes clusters on demand on provided Kubernetes
    management clusters.
  contact:
    name: "Loic Blot"
  version: 1.0.0
servers: []
paths:
  # Cluster management
  /v1/clusters:
    post:
      summary: Create a new cluster
      operationId: createCluster
      security:
        - bearerAuth: []
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cluster"
      responses:
        "201":
          description: Cluster created, returns hydrated cluster
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cluster"
        "400":
          description: Invalid input
          schema:
            $ref: "#/components/schemas/Error"
        "404":
          description: Something not found
          schema:
            $ref: "#/components/schemas/Error"
        "409":
          description: Cluster already exists
    get:
      summary: List all clusters
      operationId: listClusters
      security:
        - bearerAuth: []
        - basic: []
      responses:
        "200":
          description: List of clusters
          content:
            application/json:
              schema:
                type: object
                properties:
                  clusters:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cluster"
                  warnings:
                    type: array
                    items:
                      type: string
                required:
                  - clusters
        "404":
          description: No cluster found
  /v1/clusters/{region}/{clusterId}:
    get:
      summary: Get a cluster
      operationId: getCluster
      security:
        - bearerAuth: []
        - basicAuth: []
      parameters:
        - name: clusterId
          in: path
          required: true
          description: Cluster ID
          schema:
            type: string
        - name: region
          in: path
          required: true
          description: Cluster region
          schema:
            type: string
      responses:
        "200":
          description: Cluster found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cluster"
        "404":
          description: Cluster not found
    delete:
      summary: Delete a cluster
      operationId: deleteCluster
      security:
        - bearerAuth: []
        - basicAuth: []
      parameters:
        - name: clusterId
          in: path
          required: true
          description: Cluster ID
          schema:
            type: string
        - name: region
          in: path
          required: true
          description: Cluster region
          schema:
            type: string
      responses:
        "204":
          description: Cluster deleted
        "404":
          description: Cluster not found
  /v1/registrars:
    get:
      summary: List all management clusters
      operationId: listRegistrarClusters
      security:
        - bearerAuth: [cluster_admin]
        - basicAuth: [cluster_admin]
      responses:
        "200":
          description: List of management clusters
          content:
            application/json:
              schema:
                type: object
                properties:
                  clusters:
                    type: array
                    items:
                      $ref: "#/components/schemas/RegistrarCluster"
                  warnings:
                    type: array
                    items:
                      type: string
                required:
                  - clusters
        "404":
          description: No management cluster found
    post:
      summary: Create a new management cluster
      operationId: createRegistrarCluster
      security:
        - bearerAuth: [cluster_admin]
        - basicAuth: [cluster_admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrarCluster"
      responses:
        "201":
          description: Management cluster created, returns hydrated management cluster
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrarCluster"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Management cluster already exists

  /v1/registrars/{clusterRegistrarId}:
    get:
      summary: Get a management cluster
      operationId: getRegistrarCluster
      security:
        - bearerAuth: [cluster_admin]
        - basicAuth: [cluster_admin]
      parameters:
        - name: clusterRegistrarId
          in: path
          required: true
          description: Management cluster ID
          schema:
            type: string
      responses:
        "200":
          description: Management cluster found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrarCluster"
        "404":
          description: Management cluster not found
    delete:
      summary: Delete a management cluster
      operationId: deleteRegistrarCluster
      security:
        - bearerAuth: [cluster_admin]
        - basicAuth: [cluster_admin]
      parameters:
        - name: clusterRegistrarId
          in: path
          required: true
          description: Management cluster ID
          schema:
            type: string
      responses:
        "204":
          description: Management cluster deleted
        "404":
          description: Management cluster not found
  # Catalog management
  /v1/catalog:
    get:
      summary: List all components in the catalog
      operationId: listCatalogComponents
      security:
        - bearerAuth: []
        - basicAuth: []
      responses:
        "200":
          description: List of components
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Catalog"
        "404":
          description: No component found
  /v1/catalog/components:
    post:
      summary: Add a new component to the catalog
      operationId: addCatalogComponent
      security:
        - bearerAuth: [catalog_admin]
        - basicAuth: [catalog_admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CatalogComponent"
      responses:
        "201":
          description: Component added to the catalog
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogComponent"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Component already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/catalog/components/{componentName}:
    get:
      summary: Get a component in the catalog
      operationId: getCatalogComponent
      security:
        - bearerAuth: []
        - basicAuth: []
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component name
          schema:
            type: string
      responses:
        "200":
          description: Component found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogComponent"
        "404":
          description: Component not found
    delete:
      summary: Delete a component from the catalog
      operationId: deleteCatalogComponent
      security:
        - bearerAuth: [catalog_admin]
        - basicAuth: [catalog_admin]
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component name
          schema:
            type: string
      responses:
        "204":
          description: Component deleted
        "404":
          description: Component not found
        "409":
          description: Component cannot be deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/catalog/components/{componentName}/versions:
    post:
      summary: Add a new component version to the catalog
      operationId: addCatalogComponentVersion
      security:
        - bearerAuth: [catalog_admin]
        - basicAuth: [catalog_admin]
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component name
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CatalogComponentVersion"
      responses:
        "201":
          description: Component version added to the catalog
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogComponentVersion"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Component version already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/catalog/components/{componentName}/versions/{componentVersion}:
    get:
      summary: Get a component version in the catalog
      operationId: getCatalogComponentVersion
      security:
        - bearerAuth: []
        - basicAuth: []
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component name
          schema:
            type: string
        - name: componentVersion
          in: path
          required: true
          description: Component version
          schema:
            type: string
      responses:
        "200":
          description: Component version found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatalogComponentVersion"
        "404":
          description: Component version not found
    delete:
      summary: Delete a component version from the catalog
      operationId: deleteCatalogComponentVersion
      security:
        - bearerAuth: [catalog_admin]
        - basicAuth: [catalog_admin]
      parameters:
        - name: componentName
          in: path
          required: true
          description: Component name
          schema:
            type: string
        - name: componentVersion
          in: path
          required: true
          description: Component version
          schema:
            type: string
      responses:
        "204":
          description: Component version deleted
        "404":
          description: Component version not found
        "409":
          description: Component version cannot be deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    # Cluster related schemas
    Kubeconfig:
      type: string
    ClusterStatus:
      type: object
      properties:
        online:
          type: boolean
        phase:
          type: string
      required:
        - online
        - phase
    Cluster:
      type: object
      properties:
        name:
          type: string
        region:
          type: string
        id:
          type: string
        version:
          type: string
        kubeconfig:
          $ref: "#/components/schemas/Kubeconfig"
        status:
          $ref: "#/components/schemas/ClusterStatus"
      required:
        - name
        - region
        - version
    RegistrarCluster:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        region:
          type: string
        kubeconfig:
          $ref: "#/components/schemas/Kubeconfig"
      required:
        - name
        - region
    # Catalog related schemas
    CatalogComponent:
      type: object
      properties:
        name:
          type: string
        versions:
          type: array
          items:
            type: string
        latest_version:
          type: string
        short_description:
          type: string
        description:
          type: string
        url:
          type: string
        icon:
          type: string
        published:
          type: boolean
      required:
        - name
        - short_description
        - description
        - url
        - icon
    CatalogComponentVersion:
      type: object
      properties:
        version:
          type: string
        description:
          type: string
        publication_date:
          type: string
        enabled:
          type: boolean
      required:
        - version
        - description
        - publication_date
    Catalog:
      type: object
      properties:
        components:
          type: array
          items:
            $ref: "#/components/schemas/CatalogComponent"
      required:
        - components
