apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: catalogcomponentversions.malygos.00n.fr
spec:
  group: malygos.00n.fr
  names:
    kind: CatalogComponentVersion
    listKind: CatalogComponentVersionList
    plural: catalogcomponentversions
    singular: catalogcomponentversion
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              region:
                type: string
              kubeconfig:
                type: string
            required:
              - name
              - region