apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.malygos.00n.fr
spec:
  group: malygos.00n.fr
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              region:
                type: string
              id:
                type: string
              version:
                type: string
              kubeconfig:
                type: string
              status:
                type: object
                properties:
                  online:
                    type: boolean
                  phase:
                    type: string
                required:
                  - online
                  - phase
            required:
              - name
              - region
              - version
    subresources:
      status: {}